import { fetchDistributeurInfo } from "@/lib/distributeurs";
import { buildEmailHtml } from "@/lib/email-template";
import { fetchRssItems, VERSION as RSS_VERSION } from "@/lib/rss";

export const runtime = "nodejs";
export const VERSION = "1.0.52";

const CRON_SECRET = process.env.CRON_SECRET;

function isAuthorized(req) {
  if (!CRON_SECRET) return true;
  const { searchParams } = new URL(req.url);
  const secret = searchParams.get("secret") || "";
  return secret === CRON_SECRET;
}

async function enrichItemsWithDistributeurs(items) {
  if (!Array.isArray(items) || items.length === 0) return [];
  const results = await Promise.all(
    items.map(async (item) => {
      if (!item?.link) return item;
      try {
        const info = await fetchDistributeurInfo(item.link);
        return { ...item, ...info };
      } catch {
        return item;
      }
    })
  );
  return results;
}

export async function GET(req) {
  if (!isAuthorized(req)) {
    return new Response("Unauthorized", { status: 401 });
  }

  const result = await fetchRssItems();
  if (result.error) {
    return new Response(result.error, { status: 502 });
  }

  const items = Array.isArray(result.items) ? result.items.slice(0, 10) : [];
  const enrichedItems = await enrichItemsWithDistributeurs(items);
  const html = buildEmailHtml({
    title: "RappelConso latest items",
    intro: "Preview email: latest 10 items from the RSS feed.",
    sections: [{ title: "Latest 10 items", items: enrichedItems }],
    footer: `Preview generated by email preview API (rss ${RSS_VERSION}).`
  });

  return new Response(html, {
    status: 200,
    headers: { "content-type": "text/html; charset=utf-8" }
  });
}
